[versions]
kotlin = "1.8.0"
gradleAndroid = "8.0.0"
daggerHilt = "2.46"
coroutines = "1.6.3"
coreKtx = "1.10.1"
appCompat = "1.6.1"
material = "1.9.0"
lifecycle = "2.5.1"
room = "2.6.1"
firebaseBom = "33.1.1"
navigation = "2.7.1"
retrofit = "2.9.0"
okhttp = "4.10.0"
constraintLayout = "2.1.4"
fragment = "1.7.0"
recyclerview = "1.3.2"
compose = "1.4.1"
composeMaterial = "1.3.1"
composeMaterial3 = "1.1.0"
composeActivity = "1.6.1"
glide = "4.13.0"

[libraries]
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebaseStorage = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebaseBom" }
firebaseFirestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseBom" }
firebaseAuth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseBom" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerHilt" }
navigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
viewBindingDelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-full", version = "1.5.9" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
junit = { module = "junit:junit", version = "4.13.2" }
mockito = { module = "org.mockito:mockito-core", version = "4.1.0" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
androidxJunit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradleAndroid" }
androidLibrary = { id = "com.android.library", version.ref = "gradleAndroid" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
