[versions]
kotlin = "1.9.24"
gradleAndroid = "8.4.1"
daggerHilt = "2.51.1"
coroutines = "1.8.0"
coreKtx = "1.13.1"
appCompat = "1.7.0"
material = "1.12.0"
lifecycle = "2.8.4"
room = "2.6.1"
firebaseBom = "33.1.1"
firebaseStorage = "21.0.0"
firebaseFirestore = "25.0.0"
firebaseAuth = "23.0.0"
navigation = "2.7.7"
navigationSafeArgs = "2.7.7"
googleServices = "4.4.2"
retrofit = "2.11.0"
okhttp = "4.12.0"
constraintLayout = "2.1.4"
fragment = "1.8.2"
recyclerview = "1.3.2"
compose = "1.6.8"
composeMaterial = "1.6.8"
composeMaterial3 = "1.2.1"
composeActivity = "1.9.1"
glide = "4.16.0"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"
mockk = "1.13.12"
mockkAgent = "1.13.12"
junit = "4.12"
mockito = "5.7.0"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"
fragmentTesting = "1.8.2"
truth = "1.4.2"
androidxTestRunner = "1.6.1"
navigationTesting = "2.7.7"
robolectric = "4.5.1"


[libraries]
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
firebaseStorage = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebaseStorage" }
firebaseFirestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestore" }
firebaseAuth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuth" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerHilt" }
navigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigationSafeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgs" }
googleServices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
viewBindingDelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate-full", version = "1.5.9" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockkAndroid = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockkAgent = { module = "io.mockk:mockk-agent", version.ref = "mockkAgent" }
coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
espressoContrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoCore" }
espressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoCore" }
fragmentTesting = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTesting" }
composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
playServicesLocation = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
playServicesMaps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
hiltTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "daggerHilt" }
androidxTestRunner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
navigationTesting = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "gradleAndroid" }
androidLibrary = { id = "com.android.library", version.ref = "gradleAndroid" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
